services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - lab2_net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=usuarios_db
    networks:
      - lab2_net

  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=usuarios_db
    ports:
      - "3307:3306"   # ⚠️ por si tienes MySQL en 3306 local
    networks:
      - lab2_net

networks:
  lab2_net:
